FROM ubi8/ubi:8.3

MAINTAINER aziz elwaddi <aziz.elwaddi@nomail.nomail>

LABEL description="A custom Apache container based on UBI 8"

RUN yum install -y httpd && \
    yum clean all

RUN echo "Hello from Containerfile, that s my first LAB RH container file :)" > /var/www/html/index.html

EXPOSE 80

CMD ["httpd", "-D", "FOREGROUND"]
